builds:
  - main: cmd/process-exporter/main.go
    binary: cmd/process-exporter
    flags: -tags netgo
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64
      - ppc64le
release:
  draft: false
  prerelease: false
dockers:
  - image: ncabatoff/process-exporter
    dockerfile: Dockerfile.goreleaser
    binary: cmd/process-exporter
    goos: linux
    goarch: amd64
    tag_templates:
      - latest
      - "{{ .Version }}"
