services:
  - docker

language: go

env:
  - DEP_VERSION="0.5.0"

go:
  - 1.10.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

go_import_path: github.com/ncabatoff/process-exporter

install:
  - dep ensure

script:
  - make style vet test build integ docker

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && docker tag ncabatoff/process-exporter:$TRAVIS_TAG ncabatoff/process-exporter:latest && docker push ncabatoff/process-exporter:$TRAVIS_TAG && docker push ncabatoff/process-exporter:latest
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
